version: '3.9'

services:
  web:
    image: ghcr.io/bgribbin/buntime:latest
    restart: unless-stopped
    expose:
      - '3000'
    networks:
      - webnet

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webnet

volumes:
  caddy_data:
  caddy_config:

networks:
  webnet:
